/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'timestamp' : IDL.Int,
  'accuracy' : IDL.Float64,
});
export const TrackingSession = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : IDL.Int,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'consentGiven' : IDL.Bool,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Opt(Location),
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deactivateSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getActiveSessions' : IDL.Func([], [IDL.Vec(TrackingSession)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(TrackingSession)], ['query']),
  'submitLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'timestamp' : IDL.Int,
    'accuracy' : IDL.Float64,
  });
  const TrackingSession = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : IDL.Int,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'consentGiven' : IDL.Bool,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Opt(Location),
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deactivateSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getActiveSessions' : IDL.Func([], [IDL.Vec(TrackingSession)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(TrackingSession)], ['query']),
    'submitLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };