/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionStatus = IDL.Variant({
  'expired' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
});
export const Location = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'timestamp' : IDL.Int,
  'accuracy' : IDL.Float64,
});
export const SessionOutput = IDL.Record({
  'id' : IDL.Text,
  'status' : SessionStatus,
  'expiresAt' : IDL.Int,
  'createdAt' : IDL.Int,
  'requesterName' : IDL.Text,
  'phoneNumber' : IDL.Text,
  'location' : IDL.Opt(Location),
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'expireSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllSessions' : IDL.Func([], [IDL.Vec(SessionOutput)], ['query']),
  'getSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionOutput)], ['query']),
  'submitLocation' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionStatus = IDL.Variant({
    'expired' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
  });
  const Location = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'timestamp' : IDL.Int,
    'accuracy' : IDL.Float64,
  });
  const SessionOutput = IDL.Record({
    'id' : IDL.Text,
    'status' : SessionStatus,
    'expiresAt' : IDL.Int,
    'createdAt' : IDL.Int,
    'requesterName' : IDL.Text,
    'phoneNumber' : IDL.Text,
    'location' : IDL.Opt(Location),
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'expireSession' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllSessions' : IDL.Func([], [IDL.Vec(SessionOutput)], ['query']),
    'getSession' : IDL.Func([IDL.Text], [IDL.Opt(SessionOutput)], ['query']),
    'submitLocation' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };