/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    lat: number;
    lng: number;
    timestamp: bigint;
    accuracy: number;
}
export interface SessionOutput {
    id: string;
    status: SessionStatus;
    expiresAt: bigint;
    createdAt: bigint;
    requesterName: string;
    phoneNumber: string;
    location?: Location;
    reason: string;
}
export enum SessionStatus {
    expired = "expired",
    pending = "pending",
    completed = "completed"
}
export interface backendInterface {
    createSession(phoneNumber: string, requesterName: string, reason: string): Promise<string>;
    expireSession(sessionId: string): Promise<boolean>;
    getAllSessions(): Promise<Array<SessionOutput>>;
    getSession(sessionId: string): Promise<SessionOutput | null>;
    submitLocation(sessionId: string, lat: number, lng: number, accuracy: number): Promise<boolean>;
}
import type { Location as _Location, SessionOutput as _SessionOutput, SessionStatus as _SessionStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createSession(arg0: string, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSession(arg0, arg1, arg2);
            return result;
        }
    }
    async expireSession(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.expireSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.expireSession(arg0);
            return result;
        }
    }
    async getAllSessions(): Promise<Array<SessionOutput>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSessions();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSessions();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSession(arg0: string): Promise<SessionOutput | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSession(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSession(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitLocation(arg0: string, arg1: number, arg2: number, arg3: number): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLocation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLocation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_SessionOutput_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionOutput): SessionOutput {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SessionStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionStatus): SessionStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Location]): Location | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SessionOutput]): SessionOutput | null {
    return value.length === 0 ? null : from_candid_SessionOutput_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _SessionStatus;
    expiresAt: bigint;
    createdAt: bigint;
    requesterName: string;
    phoneNumber: string;
    location: [] | [_Location];
    reason: string;
}): {
    id: string;
    status: SessionStatus;
    expiresAt: bigint;
    createdAt: bigint;
    requesterName: string;
    phoneNumber: string;
    location?: Location;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_SessionStatus_n4(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        requesterName: value.requesterName,
        phoneNumber: value.phoneNumber,
        location: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.location)),
        reason: value.reason
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: null;
} | {
    pending: null;
} | {
    completed: null;
}): SessionStatus {
    return "expired" in value ? SessionStatus.expired : "pending" in value ? SessionStatus.pending : "completed" in value ? SessionStatus.completed : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionOutput>): Array<SessionOutput> {
    return value.map((x)=>from_candid_SessionOutput_n2(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
